### ISSUE TITLE
OTR plugin

### ISSUE THREAD

**Issue by dandelionred** [flathub/im.pidgin.Pidgin#1]
Could you please consider adding the OTR plugin to the build?

**Comment by Pixelnarium** [comment]
Sorry for the late reply I did not get a notification.

The inclusion of plugins is considered and OTR was once included in the first PR build. I removed it later due to some problems. Most pidgin plugins are abandoned too, some vanished. The [upstream page](https://otr.cypherpunks.ca/) for pidgin-otr is also unreachable me right now. I may come back later.

I still have to check if a separate "plugin flatpak" is possible.

**Comment by TingPing** [comment]
Sure its possible:

- https://github.com/flathub/io.github.Hexchat.Plugin.OTR
- https://blog.tingping.se/2018/03/18/flatpaking-plugins.html

**Comment by TingPing** [comment]
Yea it will surely require some patches to Pidgin itself.

**Comment by AsciiWolf** [comment]
Any news?

**Comment by Pixelnarium** [comment]
Okay, I made a PR about this here: https://github.com/flathub/im.pidgin.Pidgin/pull/5
This includes the plugin in the standard installation. This may break when Pidgin 3 comes out, whenever this happens.

Is this okay so far?

**Comment by Pixelnarium** [comment]
It is included now.
